name = "zfs"
version = "1.0.0"

description = "Low level ZFS ioctl wrappers for Gleam"
licences = ["BSD-2-Clause"]
repository = { type = "github", user = "ryan-moeller", repo = "gleam-zfs" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
nvpair = { git = "https://github.com/ryan-moeller/gleam-nvpair" }
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
file_streams = {
  git = "https://github.com/ryan-moeller/file_streams",
  ref = "79b097ac4b4f05e33e6b230ae52113010e753efb"
}
pprint = ">= 1.0.6 and < 2.0.0"
iv = ">= 1.4.4 and < 2.0.0"
