name: "FreeBSD 15.1"

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test on FreeBSD 15.1
    steps:
      - uses: actions/checkout@v6
      - uses: vmactions/freebsd-vm@v1
        with:
          release: "15.1"
          cache-after-prepare: true
          prepare: |
            pkg install -y \
              FreeBSD-src-sys \
              erlang \
              erlang-runtime29 \
              gleam \
              mold \
              git
          run: |
            set -e
            make
            gleam test
            gleam format --check src test
